# Generated by Django 5.0.6 on 2026-06-19 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StravaToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("athlete_id", models.BigIntegerField(blank=True, null=True)),
                ("access_token", models.CharField(max_length=255)),
                ("refresh_token", models.CharField(max_length=255)),
                ("expires_at", models.DateTimeField()),
                ("scope", models.CharField(blank=True, default="", max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strava_token",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("strava", "Strava"), ("garmin", "Garmin")],
                        default="strava",
                        max_length=16,
                    ),
                ),
                ("external_id", models.CharField(max_length=64)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("sport_type", models.CharField(blank=True, default="", max_length=64)),
                ("start_date", models.DateTimeField()),
                ("distance_m", models.FloatField(default=0)),
                ("moving_time_s", models.IntegerField(default=0)),
                ("elapsed_time_s", models.IntegerField(default=0)),
                ("total_elevation_gain_m", models.FloatField(default=0)),
                ("average_speed_ms", models.FloatField(default=0)),
                ("max_speed_ms", models.FloatField(default=0)),
                ("average_heartrate", models.FloatField(blank=True, null=True)),
                ("max_heartrate", models.FloatField(blank=True, null=True)),
                ("splits", models.JSONField(blank=True, default=list)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-start_date"],
                        name="runner_acti_user_id_a187ce_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="activity",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"), name="unique_source_activity"
            ),
        ),
    ]
