# Generated by Django 5.0.6 on 2026-06-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="average_cadence",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
