# Generated by Django 5.0.6 on 2026-06-19 20:12

import django.db.models.deletion
import django.utils.timezone
import runner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0002_activity_average_cadence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachAthlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('invite_code', models.CharField(db_index=True, default=runner.models._gen_invite_code, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('invited', 'Convidado'), ('active', 'Ativo'), ('inactive', 'Inativo')], default='invited', max_length=12)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_links', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invited_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('sleep_quality', models.IntegerField(blank=True, null=True)),
                ('soreness', models.IntegerField(blank=True, null=True)),
                ('stress', models.IntegerField(blank=True, null=True)),
                ('resting_hr', models.IntegerField(blank=True, null=True)),
                ('hrv_ms', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='manual', max_length=8)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_coach', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('resting_hr', models.IntegerField(blank=True, null=True)),
                ('max_hr', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_distance_m', models.FloatField()),
                ('goal_label', models.CharField(blank=True, default='', max_length=64)),
                ('goal_race_date', models.DateField()),
                ('goal_time_s', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('weekly_base_km', models.FloatField(default=0)),
                ('peak_weekly_km', models.FloatField(default=0)),
                ('generated_by', models.CharField(default='rules', max_length=8)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='active', max_length=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlannedWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('coach', 'Treinador'), ('ai', 'IA'), ('self', 'Próprio atleta')], default='coach', max_length=8)),
                ('date', models.DateField()),
                ('workout_type', models.CharField(choices=[('easy', 'Regenerativo / leve'), ('long', 'Longão'), ('tempo', 'Ritmo / limiar'), ('interval', 'Intervalado / tiros'), ('fartlek', 'Fartlek'), ('strides', 'Educativos / progressivo'), ('race', 'Prova'), ('rest', 'Descanso'), ('cross', 'Cross-training')], default='easy', max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('target_distance_m', models.FloatField(blank=True, null=True)),
                ('target_duration_s', models.IntegerField(blank=True, null=True)),
                ('target_pace_low_s', models.IntegerField(blank=True, null=True)),
                ('target_pace_high_s', models.IntegerField(blank=True, null=True)),
                ('structure', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('planned', 'Planejado'), ('completed', 'Realizado'), ('missed', 'Perdido'), ('skipped', 'Dispensado')], default='planned', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_workouts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_workouts', to=settings.AUTH_USER_MODEL)),
                ('matched_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_workouts', to='runner.activity')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts', to='runner.trainingplan')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('rpe', models.IntegerField(blank=True, null=True)),
                ('feeling', models.CharField(blank=True, choices=[('great', 'Ótimo 😀'), ('good', 'Bem 🙂'), ('ok', 'Ok 😐'), ('tired', 'Cansado 😕'), ('bad', 'Mal 😣')], default='', max_length=8)),
                ('soreness', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='runner.activity')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('planned_workout', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='runner.plannedworkout')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='coachathlete',
            constraint=models.UniqueConstraint(condition=models.Q(('athlete__isnull', False)), fields=('coach', 'athlete'), name='unique_coach_athlete'),
        ),
        migrations.AddConstraint(
            model_name='dailycheckin',
            constraint=models.UniqueConstraint(fields=('athlete', 'date'), name='unique_athlete_checkin_day'),
        ),
        migrations.AddIndex(
            model_name='plannedworkout',
            index=models.Index(fields=['athlete', 'date'], name='runner_plan_athlete_5c1a48_idx'),
        ),
    ]
