# Generated by Django 5.0.6 on 2026-06-20 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0003_coachathlete_dailycheckin_profile_trainingplan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('weeks_of_data', models.IntegerField(default=0)),
                ('activities_count', models.IntegerField(default=0)),
                ('weekly_volume_km', models.FloatField(default=0)),
                ('volume_trend', models.CharField(default='stable', max_length=16)),
                ('runs_per_week', models.IntegerField(default=0)),
                ('longest_run_km', models.FloatField(default=0)),
                ('peak_weekly_km', models.FloatField(default=0)),
                ('easy_pace_s', models.IntegerField(blank=True, null=True)),
                ('threshold_pace_s', models.IntegerField(blank=True, null=True)),
                ('recent_effort_pace_s', models.IntegerField(blank=True, null=True)),
                ('recent_effort_distance_m', models.FloatField(blank=True, null=True)),
                ('acwr', models.FloatField(blank=True, null=True)),
                ('acwr_zone', models.CharField(blank=True, default='', max_length=16)),
                ('consistency_pct', models.IntegerField(default=0)),
                ('experience_level', models.CharField(default='beginner', max_length=16)),
                ('confidence', models.CharField(default='low', max_length=8)),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
