# Generated by Django 5.0.6 on 2026-06-21 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0004_fitnessprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_per_week', models.IntegerField(default=4)),
                ('available_days', models.JSONField(default=list)),
                ('preferred_long_day', models.IntegerField(default=6)),
                ('preferred_time', models.CharField(choices=[('morning', 'Manhã'), ('afternoon', 'Tarde'), ('evening', 'Noite'), ('vary', 'Varia')], default='vary', max_length=10)),
                ('does_strength', models.BooleanField(default=False)),
                ('surface', models.CharField(choices=[('road', 'Rua / asfalto'), ('trail', 'Trail / montanha'), ('both', 'Ambos')], default='road', max_length=8)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('goal_note', models.TextField(blank=True, default='')),
                ('injury_history', models.TextField(blank=True, default='')),
                ('has_pain_now', models.BooleanField(default=False)),
                ('pain_where', models.CharField(blank=True, default='', max_length=200)),
                ('health_notes', models.TextField(blank=True, default='')),
                ('medical_clearance', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
