# Generated by Django 5.0.6 (hand-written; CopilotChat + TrainingPlan status "inactive")

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0005_anamnese'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='status',
            field=models.CharField(
                choices=[
                    ('active', 'Ativo'),
                    ('inactive', 'Inativo'),
                    ('completed', 'Concluído'),
                    ('cancelled', 'Cancelado'),
                ],
                default='active',
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name='CopilotChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
