# Generated by Django 5.0.6 (hand-written; CoachSuggestion + Profile.coach_autonomy)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0006_copilotchat_trainingplan_status_inactive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coach_autonomy',
            field=models.CharField(
                choices=[
                    ('suggest', 'Só sugerir (você decide)'),
                    ('auto', 'Ajustar e avisar'),
                    ('off', 'Não interferir'),
                ],
                default='suggest',
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name='CoachSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=8)),
                ('reasons', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceita'), ('declined', 'Mantido pelo atleta'), ('auto', 'Aplicada automaticamente'), ('expired', 'Expirada')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
