# Generated by Django 5.0.6 on 2026-06-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0009_cycleevent_cycleprofile_cyclesymptom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Mulher'), ('M', 'Homem')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
